spring:

  application:
    name: kettu

  mvc:
    throw-exception-if-no-handler-found: true # Handler topilmasa xato otish
  web:
    resources:
      add-mappings: false # Static resurslarni qidirishni to'xtatish (API uchun shart)

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB

  security:
    oauth2:
      client:
        registration:
          google:
            # prod
            client-id: 747364489357-qr0dm321jo33pq4v8g4m2896dhju87cn.apps.googleusercontent.com
            client-secret: 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
            # local (currently commented out)
            # client-id: 747364489357-qr0dm321jo33pq4v8g4m2896dhju87cn.apps.googleusercontent.com
            # client-secret: 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

  datasource:
    url: jdbc:postgresql://localhost:5433/kettu
    username: postgres
    password: wtmlopuhfgfdaz
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

cloudflare:
  r2:
    access-key: 2612357a234fa7657af4c36ee51531e2
    secret-key: 1926a91bf05fe064ad37d14f6e7d1b82ca862439368bd6e193867104b57e6355
    region: auto
    endpoint: https://7331730e9e5c69b9c7599dc3151cbb36.r2.cloudflarestorage.com
    bucket: khorunaliyev-kettu

logging:
  level:
    org.hibernate:
      SQL: DEBUG
      type:
        descriptor:
          sql:
            BasicBinder: TRACE

