CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA public;


--
-- TOC entry 5976 (class 0 OID 0)
-- Dependencies: 2
-- Name: EXTENSION postgis; Type: COMMENT; Schema: -; Owner:
--

COMMENT ON EXTENSION postgis IS 'PostGIS geometry and geography spatial types and functions';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 221 (class 1259 OID 71560)
-- Name: app_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_user (
    id bigint NOT NULL,
    background_image character varying(500),
    bio character varying(500),
    created_places_count integer NOT NULL,
    email character varying(255) NOT NULL,
    image character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    visited_places_count integer NOT NULL,
    first_login boolean DEFAULT false NOT NULL
);


ALTER TABLE public.app_user OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 71559)
-- Name: app_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.app_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 71574)
-- Name: category; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.category (
    id integer NOT NULL,
    active_item_count integer NOT NULL,
    name character varying(100) NOT NULL
);


ALTER TABLE public.category OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 71573)
-- Name: category_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 71582)
-- Name: category_tags; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.category_tags (
    category_id integer NOT NULL,
    tag_id integer NOT NULL
);


ALTER TABLE public.category_tags OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 71590)
-- Name: country; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.country (
    id integer NOT NULL,
    active_item_count integer NOT NULL,
    name character varying(56) NOT NULL
);


ALTER TABLE public.country OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 71589)
-- Name: country_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.country ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.country_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 72842)
-- Name: district; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.district (
    id integer NOT NULL,
    active_item_count integer NOT NULL,
    geom public.geometry(MultiPolygon,4326) NOT NULL,
    name character varying(100) NOT NULL,
    region_id integer NOT NULL
);


ALTER TABLE public.district OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 72841)
-- Name: district_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.district ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.district_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 241 (class 1259 OID 72939)
-- Name: liked_users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.liked_users (
    place_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.liked_users OWNER TO postgres;

--
-- TOC entry 243 (class 1259 OID 72947)
-- Name: place; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.place (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    description character varying(500) NOT NULL,
    likes_count integer DEFAULT 0 NOT NULL,
    name character varying(50) NOT NULL,
    photo_count integer NOT NULL,
    status character varying(13) NOT NULL,
    visited_count integer DEFAULT 0 NOT NULL,
    created_by bigint NOT NULL,
    updated_by bigint NOT NULL,
    category_id integer NOT NULL,
    CONSTRAINT place_status_check CHECK (((status)::text = ANY ((ARRAY['UPLOADING'::character varying, 'IN_MODERATION'::character varying, 'ACTIVE'::character varying, 'REJECTED'::character varying, 'INACTIVE'::character varying, 'FAILED'::character varying])::text[])))
);


ALTER TABLE public.place OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 72946)
-- Name: place_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.place ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.place_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 245 (class 1259 OID 72970)
-- Name: place_location; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.place_location (
    id bigint NOT NULL,
    point public.geography(Point,4326) NOT NULL,
    country_id integer NOT NULL,
    district_id integer NOT NULL,
    place_id bigint NOT NULL,
    region_id integer NOT NULL
);


ALTER TABLE public.place_location OWNER TO postgres;

--
-- TOC entry 244 (class 1259 OID 72969)
-- Name: place_location_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.place_location ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.place_location_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 247 (class 1259 OID 72984)
-- Name: place_photo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.place_photo (
    id bigint NOT NULL,
    image character varying(255) NOT NULL,
    is_main boolean NOT NULL,
    is_processing boolean NOT NULL,
    place_id bigint NOT NULL
);


ALTER TABLE public.place_photo OWNER TO postgres;

--
-- TOC entry 246 (class 1259 OID 72983)
-- Name: place_photo_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.place_photo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.place_photo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 248 (class 1259 OID 72994)
-- Name: place_tags; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.place_tags (
    place_id bigint NOT NULL,
    tag_id integer NOT NULL
);


ALTER TABLE public.place_tags OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 71643)
-- Name: region; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.region (
    id integer NOT NULL,
    active_item_count integer NOT NULL,
    name character varying(85) NOT NULL,
    country_id integer NOT NULL
);


ALTER TABLE public.region OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 71642)
-- Name: region_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.region ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.region_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 71653)
-- Name: role; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.role (
    id integer NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.role OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 71652)
-- Name: role_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 71661)
-- Name: tag; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tag (
    id integer NOT NULL,
    name character varying(50) NOT NULL
);


ALTER TABLE public.tag OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 71660)
-- Name: tag_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tag ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 250 (class 1259 OID 73002)
-- Name: user_active_uploads; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_active_uploads (
    id bigint NOT NULL,
    place_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.user_active_uploads OWNER TO postgres;

--
-- TOC entry 249 (class 1259 OID 73001)
-- Name: user_active_uploads_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_active_uploads ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_active_uploads_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 71668)
-- Name: user_roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_roles (
    user_id bigint NOT NULL,
    role_id integer NOT NULL
);


ALTER TABLE public.user_roles OWNER TO postgres;

--
-- TOC entry 251 (class 1259 OID 73010)
-- Name: visited_users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.visited_users (
    place_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.visited_users OWNER TO postgres;

--
-- TOC entry 5744 (class 2606 OID 71572)
-- Name: app_user app_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_pkey PRIMARY KEY (id);


--
-- TOC entry 5748 (class 2606 OID 71581)
-- Name: category category_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.category
    ADD CONSTRAINT category_pkey PRIMARY KEY (id);


--
-- TOC entry 5754 (class 2606 OID 71597)
-- Name: country country_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.country
    ADD CONSTRAINT country_pkey PRIMARY KEY (id);


--
-- TOC entry 5774 (class 2606 OID 72853)
-- Name: district district_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.district
    ADD CONSTRAINT district_pkey PRIMARY KEY (id);


--
-- TOC entry 5778 (class 2606 OID 72945)
-- Name: liked_users liked_users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.liked_users
    ADD CONSTRAINT liked_users_pkey PRIMARY KEY (place_id, user_id);


--
-- TOC entry 5782 (class 2606 OID 72982)
-- Name: place_location place_location_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.place_location
    ADD CONSTRAINT place_location_pkey PRIMARY KEY (id);


--
-- TOC entry 5788 (class 2606 OID 72993)
-- Name: place_photo place_photo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.place_photo
    ADD CONSTRAINT place_photo_pkey PRIMARY KEY (id);


--
-- TOC entry 5780 (class 2606 OID 72968)
-- Name: place place_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.place
    ADD CONSTRAINT place_pkey PRIMARY KEY (id);


--
-- TOC entry 5790 (class 2606 OID 73000)
-- Name: place_tags place_tags_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.place_tags
    ADD CONSTRAINT place_tags_pkey PRIMARY KEY (place_id, tag_id);


--
-- TOC entry 5758 (class 2606 OID 71651)
-- Name: region region_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.region
    ADD CONSTRAINT region_pkey PRIMARY KEY (id);


--
-- TOC entry 5762 (class 2606 OID 71659)
-- Name: role role_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role
    ADD CONSTRAINT role_pkey PRIMARY KEY (id);


--
-- TOC entry 5766 (class 2606 OID 71667)
-- Name: tag tag_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tag
    ADD CONSTRAINT tag_pkey PRIMARY KEY (id);


--
-- TOC entry 5746 (class 2606 OID 71683)
-- Name: app_user uk1j9d9a06i600gd43uu3km82jw; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT uk1j9d9a06i600gd43uu3km82jw UNIQUE (email);


--
-- TOC entry 5792 (class 2606 OID 73022)
-- Name: user_active_uploads uk1sv5fp1gpt76iyhbnivg20dj6; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_active_uploads
    ADD CONSTRAINT uk1sv5fp1gpt76iyhbnivg20dj6 UNIQUE (place_id);


--
-- TOC entry 5768 (class 2606 OID 71693)
-- Name: tag uk1wdpsed5kna2y38hnbgrnhi5b; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tag
    ADD CONSTRAINT uk1wdpsed5kna2y38hnbgrnhi5b UNIQUE (name);


--
-- TOC entry 5750 (class 2606 OID 71685)
-- Name: category uk46ccwnsi9409t36lurvtyljak; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.category
    ADD CONSTRAINT uk46ccwnsi9409t36lurvtyljak UNIQUE (name);


--
-- TOC entry 5764 (class 2606 OID 71691)
-- Name: role uk8sewwnpamngi6b1dwaa88askk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role
    ADD CONSTRAINT uk8sewwnpamngi6b1dwaa88askk UNIQUE (name);


--
-- TOC entry 5752 (class 2606 OID 71588)
-- Name: category_tags uk_category_tag; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.category_tags
    ADD CONSTRAINT uk_category_tag PRIMARY KEY (category_id, tag_id);


--
-- TOC entry 5784 (class 2606 OID 73020)
-- Name: place_location ukgshttqp6ly4kapnftitqtg1vu; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.place_location
    ADD CONSTRAINT ukgshttqp6ly4kapnftitqtg1vu UNIQUE (place_id);


--
-- TOC entry 5786 (class 2606 OID 73018)
-- Name: place_location ukha8tn98qf1fk2i5q1qm44je9l; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.place_location
    ADD CONSTRAINT ukha8tn98qf1fk2i5q1qm44je9l UNIQUE (point);


--
-- TOC entry 5760 (class 2606 OID 71689)
-- Name: region ukixr2itih2n9q41fv3qx6mbkrp; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.region
    ADD CONSTRAINT ukixr2itih2n9q41fv3qx6mbkrp UNIQUE (name);


--
-- TOC entry 5776 (class 2606 OID 72869)
-- Name: district ukkvkg405mr04cjytv1tuyh7ryr; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.district
    ADD CONSTRAINT ukkvkg405mr04cjytv1tuyh7ryr UNIQUE (name);


--
-- TOC entry 5756 (class 2606 OID 71687)
-- Name: country ukllidyp77h6xkeokpbmoy710d4; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.country
    ADD CONSTRAINT ukllidyp77h6xkeokpbmoy710d4 UNIQUE (name);


--
-- TOC entry 5794 (class 2606 OID 73009)
-- Name: user_active_uploads user_active_uploads_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_active_uploads
    ADD CONSTRAINT user_active_uploads_pkey PRIMARY KEY (id);


--
-- TOC entry 5770 (class 2606 OID 71674)
-- Name: user_roles user_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role_id);


--
-- TOC entry 5796 (class 2606 OID 73016)
-- Name: visited_users visited_users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.visited_users
    ADD CONSTRAINT visited_users_pkey PRIMARY KEY (place_id, user_id);


--
-- TOC entry 5805 (class 2606 OID 73043)
-- Name: place fk3297dq7rblawjc9n4kx9htui4; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.place
    ADD CONSTRAINT fk3297dq7rblawjc9n4kx9htui4 FOREIGN KEY (category_id) REFERENCES public.category(id);


--
-- TOC entry 5815 (class 2606 OID 73088)
-- Name: user_active_uploads fk3lcv8ukl7rpcdg33cjkg5w6uw; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_active_uploads
    ADD CONSTRAINT fk3lcv8ukl7rpcdg33cjkg5w6uw FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- TOC entry 5800 (class 2606 OID 71744)
-- Name: user_roles fk6fql8djp64yp4q9b3qeyhr82b; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fk6fql8djp64yp4q9b3qeyhr82b FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- TOC entry 5808 (class 2606 OID 73063)
-- Name: place_location fk7gn2x8vwj8n30pd3hqrsoj62f; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.place_location
    ADD CONSTRAINT fk7gn2x8vwj8n30pd3hqrsoj62f FOREIGN KEY (region_id) REFERENCES public.region(id);


--
-- TOC entry 5799 (class 2606 OID 71734)
-- Name: region fk7vb2cqcnkr9391hfn72louxkq; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.region
    ADD CONSTRAINT fk7vb2cqcnkr9391hfn72louxkq FOREIGN KEY (country_id) REFERENCES public.country(id);


--
-- TOC entry 5813 (class 2606 OID 73073)
-- Name: place_tags fk83nva20skaxn38a0rtn8crger; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.place_tags
    ADD CONSTRAINT fk83nva20skaxn38a0rtn8crger FOREIGN KEY (tag_id) REFERENCES public.tag(id);


--
-- TOC entry 5797 (class 2606 OID 71699)
-- Name: category_tags fk8ulufqq1auwixurqa6sue3k7f; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.category_tags
    ADD CONSTRAINT fk8ulufqq1auwixurqa6sue3k7f FOREIGN KEY (category_id) REFERENCES public.category(id);


--
-- TOC entry 5803 (class 2606 OID 73028)
-- Name: liked_users fkb76avyqqhaf0hl23b0kbun94e; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.liked_users
    ADD CONSTRAINT fkb76avyqqhaf0hl23b0kbun94e FOREIGN KEY (place_id) REFERENCES public.place(id);


--
-- TOC entry 5798 (class 2606 OID 71694)
-- Name: category_tags fkclr8vrg8b1cwgwjsgcd5jtj6a; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.category_tags
    ADD CONSTRAINT fkclr8vrg8b1cwgwjsgcd5jtj6a FOREIGN KEY (tag_id) REFERENCES public.tag(id);


--
-- TOC entry 5817 (class 2606 OID 73093)
-- Name: visited_users fkdy75p1fb5smcepqgq78t5vkef; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.visited_users
    ADD CONSTRAINT fkdy75p1fb5smcepqgq78t5vkef FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- TOC entry 5818 (class 2606 OID 73098)
-- Name: visited_users fkfv11yq6unxx6qwltiqnhsfc0p; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.visited_users
    ADD CONSTRAINT fkfv11yq6unxx6qwltiqnhsfc0p FOREIGN KEY (place_id) REFERENCES public.place(id);


--
-- TOC entry 5809 (class 2606 OID 73058)
-- Name: place_location fki68q72m6yr59acu6ifhprwjg6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.place_location
    ADD CONSTRAINT fki68q72m6yr59acu6ifhprwjg6 FOREIGN KEY (place_id) REFERENCES public.place(id);


--
-- TOC entry 5810 (class 2606 OID 73053)
-- Name: place_location fkiqv3dknjk7hkb3rq0mdqtnyyq; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.place_location
    ADD CONSTRAINT fkiqv3dknjk7hkb3rq0mdqtnyyq FOREIGN KEY (district_id) REFERENCES public.district(id);


--
-- TOC entry 5816 (class 2606 OID 73083)
-- Name: user_active_uploads fklocnqi1gex7q2jyri8v89ey5u; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_active_uploads
    ADD CONSTRAINT fklocnqi1gex7q2jyri8v89ey5u FOREIGN KEY (place_id) REFERENCES public.place(id);


--
-- TOC entry 5814 (class 2606 OID 73078)
-- Name: place_tags fkp1uv9a1bda17nl3b3aufadmct; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.place_tags
    ADD CONSTRAINT fkp1uv9a1bda17nl3b3aufadmct FOREIGN KEY (place_id) REFERENCES public.place(id);


--
-- TOC entry 5812 (class 2606 OID 73068)
-- Name: place_photo fkp5b9kujr9vddcaemns4he6p3m; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.place_photo
    ADD CONSTRAINT fkp5b9kujr9vddcaemns4he6p3m FOREIGN KEY (place_id) REFERENCES public.place(id);


--
-- TOC entry 5811 (class 2606 OID 73048)
-- Name: place_location fkpforvivequu8f2j5ypq4alpr2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.place_location
    ADD CONSTRAINT fkpforvivequu8f2j5ypq4alpr2 FOREIGN KEY (country_id) REFERENCES public.country(id);


--
-- TOC entry 5802 (class 2606 OID 72872)
-- Name: district fkpjyu66maoe0h5uqfhle85e5vo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.district
    ADD CONSTRAINT fkpjyu66maoe0h5uqfhle85e5vo FOREIGN KEY (region_id) REFERENCES public.region(id);


--
-- TOC entry 5806 (class 2606 OID 73038)
-- Name: place fkq1lcbkoljr2dkyiqalbf74sgs; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.place
    ADD CONSTRAINT fkq1lcbkoljr2dkyiqalbf74sgs FOREIGN KEY (updated_by) REFERENCES public.app_user(id);


--
-- TOC entry 5804 (class 2606 OID 73023)
-- Name: liked_users fkq2dqy7yedx5xtrvl047gk0i7u; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.liked_users
    ADD CONSTRAINT fkq2dqy7yedx5xtrvl047gk0i7u FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- TOC entry 5801 (class 2606 OID 71739)
-- Name: user_roles fkrhfovtciq1l558cw6udg0h0d3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkrhfovtciq1l558cw6udg0h0d3 FOREIGN KEY (role_id) REFERENCES public.role(id);


--
-- TOC entry 5807 (class 2606 OID 73033)
-- Name: place fkslgg8gr567f2uuu7ax69qkmjo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.place
    ADD CONSTRAINT fkslgg8gr567f2uuu7ax69qkmjo FOREIGN KEY (created_by) REFERENCES public.app_user(id);

